# Chapter 3: Matrices (NCERT)

## Page 1: Introduction
Matrices are a compact way to represent data and solve systems of linear equations.

They are useful in:
- solving linear equations (main motivation)
- spreadsheets (budgeting, projections)
- transformations in geometry (rotation, reflection, magnification)
- cryptography and applications in science/social sciences


In [26]:
import numpy as np

# A simple matrix (2x2)
A = np.array([[2, 1],
              [1, -1]])
A


array([[ 2,  1],
       [ 1, -1]])

## Page 2: Turning tables into matrices
Example: notebooks/pens for Radha, Fauzia, Simran can be written as a matrix.

Rows can represent people, columns can represent items (or vice versa).
The meaning depends on how you arrange the data.


In [27]:
# Rows = people, columns = [notebooks, pens]
M = np.array([
    [15, 6],   # Radha
    [10, 2],   # Fauzia
    [13, 5]    # Simran
])
M


array([[15,  6],
       [10,  2],
       [13,  5]])

## Page 3: Definition + Order of a matrix
**Matrix:** an ordered rectangular array of numbers (or functions).

If a matrix has:
- `m` rows
- `n` columns  
Then its **order** is `m × n` (read “m by n”).

General notation:
- `A = [a_{ij}]_{m×n}`
- `a_{ij}` is the element in the i-th row and j-th column
- Total number of elements = `m*n`


In [28]:
A = np.array([[-2, 5],
              [ 0, 5],
              [ 3, 6]])  # 3x2

A.shape, A[0,1], A[2,0]  # (order), a12, a31 in 1-based math indexing


((3, 2), np.int64(5), np.int64(3))

## Page 4: Representing points as matrices

A point `(x, y)` can be represented as a column matrix:

$$
\begin{bmatrix}
x \\
y
\end{bmatrix}
$$

or a row matrix `[x, y]`.

Matrices can represent vertices of shapes by stacking points.

Example 1 begins: men/women workers in factories.



In [29]:
# Column vector representation of point (0,1)
P = np.array([[0],
              [1]])
P


array([[0],
       [1]])

## Page 5: Examples
### Example 1
Workers (Men, Women) across factories I, II, III as a `3×2` matrix.

### Example 2
If a matrix has 8 elements, possible orders are factor pairs of 8:
(1,8), (8,1), (2,4), (4,2).

### Example 3
Construct matrix from a rule for `a_{ij}` (elements defined by a formula).


In [ ]:
# Example 1: 3x2 matrix (rows=factories, cols=[men, women])
workers = np.array([
    [30, 25],
    [25, 31],
    [27, 26]
])
workers

# Example 2: factor pairs for total elements
n = 8
orders = [(a, n//a) for a in range(1, n+1) if n % a == 0]
orders

# Example 3-like: build A where a_ij is defined by some rule
# We'll reproduce the page idea: define using i,j loops (1-based in math)
A = np.zeros((3,2), dtype=float)
for i in range(1, 4):      # i=1..3
    for j in range(1, 3):  # j=1..2
        A[i-1, j-1] = 0.5 * abs(i - 3*j)  # one reasonable interpretation used in the book-style example
A


array([[1. , 2.5],
       [0.5, 2. ],
       [0. , 1.5]])

## Page 6: Types of matrices

- **Column matrix:** only 1 column (m × 1)  
- **Row matrix:** only 1 row (1 × n)  
- **Square matrix:** rows = columns (n × n)  

For a square matrix, diagonal entries are:

$$
a_{11},\ a_{22},\ \ldots,\ a_{nn}
$$


In [31]:
col = np.array([[0],[3],[-1],[0.5]])   # 4x1
row = np.array([[1, -0.5, 2, 3]])      # 1x4
sq  = np.array([[1,3,-1],
                [2,4, 1],
                [3,5, 6]])

col.shape, row.shape, sq.shape, np.diag(sq)


((4, 1), (1, 4), (3, 3), array([1, 4, 6]))

## Page 7: Diagonal / Scalar / Identity
- **Diagonal matrix:** all off-diagonal elements are 0.
- **Scalar matrix:** diagonal matrix with all diagonal entries equal to the same constant k.
- **Identity matrix (I):** scalar matrix with k=1.


In [32]:
D = np.diag([1,2,3])          # diagonal
S = 3*np.eye(3)               # scalar (k=3)
I = np.eye(3)                 # identity
D, S, I


(array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]),
 array([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

## Page 8: Zero matrix and equality
- **Zero matrix (O):** all entries are 0.
- Two matrices are equal if:
  1) same order
  2) corresponding entries are equal

Examples show: equate corresponding elements to solve for unknowns.


In [33]:
O = np.zeros((2,3))
O


array([[0., 0., 0.],
       [0., 0., 0.]])

## Page 10: Matrix addition (idea)
Matrix addition adds corresponding entries:
\[
(A+B)_{ij} = A_{ij} + B_{ij}
\]
Only defined when both matrices have the **same order**.


In [34]:
A = np.array([[80, 60],
              [75, 65],
              [90, 85]])
B = np.array([[90, 50],
              [70, 55],
              [75, 75]])

A_plus_B = A + B
A_plus_B


array([[170, 110],
       [145, 120],
       [165, 160]])

## Page 11: Addition definition + Example 6
If A and B are both m×n, then A+B is m×n.
If orders differ, A+B is not defined.


In [35]:
A = np.array([[ 3,  1, -1],
              [ 2,  3,  0]])
B = np.array([[ 2,  np.sqrt(5),  1],
              [ 1, -2,           1.5]])

A + B


array([[5.        , 3.23606798, 0.        ],
       [3.        , 1.        , 1.5       ]])

## Page 12: Scalar multiplication

If `k` is a number and `A` is a matrix:

$$
(kA)_{ij} = k \cdot A_{ij}
$$

Negative of a matrix:

$$
-A = (-1)A
$$


In [36]:
A = np.array([[3, 1, 1.5],
              [5, 7, -3],
              [2, 0, 5]], dtype=float)

3*A, -A


(array([[ 9. ,  3. ,  4.5],
        [15. , 21. , -9. ],
        [ 6. ,  0. , 15. ]]),
 array([[-3. , -1. , -1.5],
        [-5. , -7. ,  3. ],
        [-2. , -0. , -5. ]]))

## Page 13: Difference of matrices
\[
A - B = A + (-1)B
\]
Example: compute `2A - B` using scalar multiplication and subtraction.


In [37]:
A = np.array([[ 1, 2, 3],
              [ 2, 3, 1]])
B = np.array([[ 3, 1, 3],
              [ 1, 0, 2]])

2*A - B


array([[-1,  3,  3],
       [ 3,  6,  0]])

## Pages 14–16: Key properties + solving for unknowns

### Properties of matrix addition
- **Commutative:** `A + B = B + A`
- **Associative:** `(A + B) + C = A + (B + C)`
- **Additive identity:** `A + O = A`  (where `O` is the zero matrix)
- **Additive inverse:** `A + (-A) = O`

### Solving for an unknown matrix
If you have an equation like:

$$
2A + 3X = 5B
$$

Then isolate \(X\):

$$
3X = 5B - 2A
$$

$$
X = \frac{1}{3}(5B - 2A)
$$


In [38]:
A = np.array([[ 8,  0],
              [ 4, -2],
              [ 3,  6]])
B = np.array([[ 2, -2],
              [ 4, -2],
              [-5,  1]])

X = (5*B - 2*A)/3
X


array([[ -2.        ,  -3.33333333],
       [  4.        ,  -2.        ],
       [-10.33333333,  -2.33333333]])

## Pages 17–19: Matrix multiplication

### When is the product \(AB\) defined?
Multiplication \(AB\) is defined when:

- **Number of columns of \(A\)** = **Number of rows of \(B\)**

### Size (order) of the product
If \(A\) is an \(m \times n\) matrix and \(B\) is an \(n \times p\) matrix, then:

- \(AB\) is an \(m \times p\) matrix.

### Formula for entries of \(AB\)
The entry in the \(i\)-th row and \(k\)-th column of \(AB\) is:

$$
(AB)_{ik} = \sum_{j=1}^{n} a_{ij}\, b_{jk}
$$

### Interpretation
A common real-life interpretation is:

- **requirements × prices = total cost**


In [39]:
requirements = np.array([[2, 5],
                         [8,10]])      # 2x2
prices = np.array([[5],
                   [50]])             # 2x1

money = requirements @ prices         # matrix product
money


array([[260],
       [540]])

In [40]:
A = np.array([[6, 9],
              [2, 3]])
B = np.array([[2, 6, 0],
              [7, 9, 8]])

A @ B


array([[ 75, 117,  72],
       [ 25,  39,  24]])

## Pages 20–21: Important facts
- AB may be defined but BA may not be defined.
- Even if both are defined, generally AB ≠ BA (non-commutative).
- It is possible that AB = O even when A and B are not zero matrices.


In [41]:
A = np.array([[1,2,3],
              [4,2,5]])      # 2x3
B = np.array([[2,3],
              [4,5],
              [2,1]])        # 3x2

AB = A @ B
BA = B @ A
AB, BA.shape


(array([[16, 16],
        [26, 27]]),
 (3, 3))

In [42]:
A = np.array([[0, 1],
              [0, 2]])
B = np.array([[3, 5],
              [0, 0]])

A @ B


array([[0, 0],
       [0, 0]])

## Pages 22–24: Properties of multiplication
- Associative: (AB)C = A(BC)
- Distributive: A(B+C)=AB+AC and (A+B)C=AC+BC
Also shown: expressions like A^3 - 23A - 40I = O for a specific matrix A.


In [43]:
A = np.array([[1,1,1],
              [2,0,3],
              [3,1,2]])
B = np.array([[1,0,1],
              [0,2,0],
              [1,4,1]])
C = np.array([[3,2,4,2],
              [1,2,3,4],
              [2,0,2,1]])

left  = (A @ B) @ C
right = A @ (B @ C)

np.allclose(left, right)


True

## Pages 25–27: Exercise 3.2 (practice)
Contains mixed practice on:
- A+B, A-B, kA-C
- AB and BA
- solving for X,Y from matrix equations
- trig matrices and identities


## Pages 28–30: Transpose (A^T)
Transpose swaps rows and columns.
If A is m×n, then A^T is n×m.

Properties:
- (A^T)^T = A
- (kA)^T = kA^T
- (A+B)^T = A^T + B^T
- (AB)^T = B^T A^T


In [44]:
A = np.array([[3,3,2],
              [4,2,0]])
B = np.array([[2,1,2],
              [1,2,4]])

(A + B).T, A.T + B.T


(array([[5, 5],
        [4, 4],
        [4, 4]]),
 array([[5, 5],
        [4, 4],
        [4, 4]]))

In [45]:
A = np.array([[-2, 4, 5]])      # 1x3
B = np.array([[1,3,6],
              [-1,-2,0],
              [2,1,4]])         # 3x3

left = (A @ B).T
right = B.T @ A.T
np.allclose(left, right)


True

## Pages 30–33: Symmetric and skew-symmetric

- **Symmetric matrix:** \(A^T = A\)
- **Skew-symmetric matrix:** \(A^T = -A\)  
  (so the diagonal entries must be zero)

### Key facts
- \(A + A^T\) is **symmetric**
- \(A - A^T\) is **skew-symmetric**
- Any square matrix \(A\) can be written as:

$$
A = \frac{1}{2}(A + A^T) + \frac{1}{2}(A - A^T)
$$


In [46]:
A = np.array([[2, -1, 4],
              [1,  3, 0],
              [7,  2, 5]], dtype=float)

S = 0.5 * (A + A.T)   # symmetric part
K = 0.5 * (A - A.T)   # skew-symmetric part

# checks
is_sym = np.allclose(S, S.T)
is_skew = np.allclose(K, -K.T)
rebuild = np.allclose(A, S + K)

is_sym, is_skew, rebuild


(True, True, True)

## Pages 35–36: Inverse of a matrix

A square matrix \(A\) is **invertible** if there exists a matrix \(A^{-1}\) such that:

$$
AA^{-1} = A^{-1}A = I
$$

### Important points
- Only **square matrices** can have inverses.
- The inverse (if it exists) is **unique**.
- If \(A\) and \(B\) are invertible, then:

$$
(AB)^{-1} = B^{-1}A^{-1}
$$


In [47]:
A = np.array([[2,3],
              [1,2]], dtype=float)

A_inv = np.linalg.inv(A)
I_check = A @ A_inv

A_inv, I_check


(array([[ 2., -3.],
        [-1.,  2.]]),
 array([[1., 0.],
        [0., 1.]]))


## Pages 37–39: Miscellaneous examples
Includes:
- powers of a rotation-like matrix using induction
- if A,B symmetric then AB symmetric iff AB=BA (they commute)
- solving matrix equations by equating entries


In [48]:
theta = np.pi/6
A = np.array([[np.cos(theta),  np.sin(theta)],
              [-np.sin(theta), np.cos(theta)]], dtype=float)

n = 5
A_n = np.linalg.matrix_power(A, n)

target = np.array([[np.cos(n*theta),  np.sin(n*theta)],
                   [-np.sin(n*theta), np.cos(n*theta)]], dtype=float)

np.allclose(A_n, target)


True

## Pages 40–41: Summary checklist
You should be able to:
- identify order, entries a_{ij}
- classify matrices: row/column/square/diagonal/scalar/identity/zero
- test equality (same order + same corresponding entries)
- do addition, subtraction, scalar multiplication
- multiply matrices (dimension rule + dot-sum formula)
- use transpose properties
- test symmetric and skew-symmetric, and decompose A into symmetric+skew parts
- compute inverse for invertible square matrices


In [49]:
import numpy as np

rng = np.random.default_rng(0)

def random_matrix(m, n, low=-5, high=6):
    return rng.integers(low, high, size=(m,n))

# 1) Addition/subtraction practice
A = random_matrix(3,3)
B = random_matrix(3,3)
print("A=\n", A, "\n")
print("B=\n", B, "\n")
print("A+B=\n", A+B, "\n")
print("A-B=\n", A-B, "\n")

# 2) Multiplication practice (dimension rule)
A = random_matrix(2,3)
B = random_matrix(3,4)
print("A shape:", A.shape, "B shape:", B.shape)
print("AB shape:", (A@B).shape)

# 3) Transpose and symmetric/skew checks
M = random_matrix(3,3)
S = (M + M.T)/2
K = (M - M.T)/2
print("Symmetric check:", np.allclose(S, S.T))
print("Skew check:", np.allclose(K, -K.T))


A=
 [[ 4  2  0]
 [-3 -2 -5]
 [-5 -5 -4]] 

B=
 [[3 2 5]
 [0 1 5]
 [3 1 0]] 

A+B=
 [[ 7  4  5]
 [-3 -1  0]
 [-2 -4 -4]] 

A-B=
 [[  1   0  -5]
 [ -3  -3 -10]
 [ -8  -6  -4]] 

A shape: (2, 3) B shape: (3, 4)
AB shape: (2, 4)
Symmetric check: True
Skew check: True
